version: 0.0
os: linux
files:
  - source: /
    destination: /home/ec2-user/talentbuildersapi
hooks:
  ApplicationStop:
    - location: stop_server.sh
      timeout: 300
      runas: ec2-user
  BeforeInstall:
    - location: install_dependencies.sh
      timeout: 300
      runas: ec2-user
  ApplicationStart:
    - location: start_server.sh
      timeout: 300
      runas: ec2-user