version: 0.1.0
phases:
  build:
    commands:
      - echo build started on `date`
      - mvn test
  deploy_build:
    commands:
      - echo build deployed started on `date`
      - mvn package
artifacts:
  files:
    - target/*.jar
