version: 0.1.0
phases:
  build:
    commands:
      - echo build started on `date`
      # - mvn test
      - docker build -t talentbuildersapi .
  deploy_build:
    commands:
      - echo build deployed started on `date`
      # - mvn package
  post_build:
    commands:
      - docker save talentbuildersapi | gzip -c > talentbuildersapi.tar.gz
artifacts:
  files:
    - talentbuildersapi.tar.gz
    - appspec.yml
    - scripts/*
  discard-paths: yes
