version: 0.2

phases:
  build:
    commands:
      - echo build started on `date`
      - docker build -t talentbuildersapi .
  post_build:
    commands:
      - docker save talentbuildersapi | gzip -c > talentbuildersapi.tar.gz
artifacts:
  files:
    - talentbuildersapi.tar.gz
    - appspec.yml
    - scripts/*
  discard-paths: yes
