# application.yml
spring:
  mail:
    default-encoding: UTF-8
    host: smtp.gmail.com
    username: habeexdev@gmail.com
    password: Habeex11@
    port: 465
    properties:
      mail:
        smtp:
          port: 25
          auth: true
          starttls:
              enable: true
          socketFactory:
            port: 465
            class: javax.net.ssl.SSLSocketFactory
            fallback: false
    protocol: smtp
    test-connection: false